version: "1.1"
services:
  schedule:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-client
    environment:
      - VITE_API_URL: ${VITE_API_URL}
      - VITE_AUTH_URL: ${VITE_AUTH_URL}
    ports:
      - '3003:3003'
    stdin_open: true
    tty: true
    networks:
      net_con:
        ipv4_address: 10.5.0.6

networks:
  net_con:
    external:
      name: "schedule-network"
